version = "3.7.15"
style = defaultWithAlign
maxColumn = 150
lineEndings = unix
importSelectors = singleLine

project {
  git = true
}

align = most

align {
  tokens = [ {code = "=>", owner = "Case|Type.Arg.ByName"}, "=", "<-", "->", "%", "%%", "should", "shouldBe", "must", "mustBe", ":" ]
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = false
}

binPack {
  parentConstructors = false
}

continuationIndent {
  callSite = 2
  defnSite = 2
}

newlines {
  penalizeSingleSelectMultiArgList = false
  sometimesBeforeColonInMethodReturnType = true
}

rewrite {
  rules = [RedundantBraces, RedundantParens, AsciiSortImports]
  redundantBraces {
    maxLines = 100
    includeUnitMethods = true
    stringInterpolation = true
  }
}

spaces {
  inImportCurlyBraces = false
  beforeContextBoundColon = false
}
runner.dialect = scala213
fileOverride {
  "glob:**/subprojects/selectorlist/processor/src/test/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/portal/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/core/databases/src/it/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/springboard/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/springboard/src/test/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/core/databases/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/jobs/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/selectorlist/processor/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/eoyDataRefresh/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/processes/selectorlistDownloaderJob/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/selectorlist/generator/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/generate/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/portal/src/it/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/selectorlist/databases/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/server/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/server/src/test/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/springboard/src/it/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/core/models/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/processes/selectorlistReprocessorJob/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/processes/selectorlistDownloader/src/main/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/selectorlist/databases/src/it/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/portal/src/test/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/subprojects/selectorlist/databases/src/test/scala/**" {
    runner.dialect = scala213source3
  }
  "glob:**/api/server/src/it/scala/**" {
    runner.dialect = scala213source3
  }
}
