addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "2.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.17.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.5")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-ci-release" % "0.7.4")
